---
title: '0607'
author: "Shanshan Hu"
date: "6/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(glmnet) # ridge and lasso
library(gam) # for gam
library(pls) # pcr pls
library(leaps) # regsubset
library(MASS) # lda qda
library(class) # knn
library(caret) # knn with prob
library(gbm) # boosting
library(boot) # cross validation
library(car) # vif, residual plots, partial residual plots
library (ROCR) 
library (pROC) # ROC AUC plot
library(tree)
library(randomForest)
library(ranger) # Random Forest
library(neuralnet) # DNN
library(e1071) # SVM
library(RandPro) # Random Projection Method 1

library(pryr) # memory count
library(MatrixModels) # sparse matrix representation
```

```{r}
setwd("D:\\Merck challenge\\qsar_train")
X = read_csv("D:\\Merck challenge\\qsar_train\\QSAR_7_train_x.csv") 
Y = read_csv("D:\\Merck challenge\\qsar_train\\QSAR_7_train_y.csv") 
# df=cbind(Y,X)

setwd("D:\\Merck challenge\\qsar_rp")
P = read_csv("result7rp1g3.csv")
P=P[,-1]
R = read_csv("7rp1g3.csv")
R = R[,-1]
# df1=cbind(Y,P[,-1])
P= as.matrix(P)
X= as.matrix(X)
R= as.matrix(R)
```

```{r}
P = scale(P, center = TRUE, scale = TRUE)
S = svd(P)
D = diag(S$d)
U = S$u
V = S$v

X = scale(X, center = TRUE, scale = TRUE)
s = svd(X)
d = diag(s$d)
u = s$u
v = s$v
```

```{r}
PTP = t(P) %*% P
PTP_e = eigen(PTP)
V1=PTP_e$vectors
# v and V sign changed => scale v by -1

PPT = P %*% t(P)
PPT_e = eigen(PPT)
U1 = PPT_e$vectors
# u = u[,1:817]

D1 = sqrt(PTP_e$values)
D1 = D1*diag(length(D1))

D11 = sqrt(PPT_e$values)
D11 = D11*diag(length(D11))

# p = u %*% d %*% t(v)
```

XTX = t(X) %*% X
XTX_e = eigen(XTX)
v1=XTX_e$vectors
# v and V sign changed => scale v by -1

XXT = X %*% t(X)
XXT_e = eigen(XXT)
u1 = XXT_e$vectors
# u = u[,1:817]

d1 = sqrt(XTX_e$values)
d1 = d1*diag(length(d1))

d11 = sqrt(XXT_e$values)
d11 = d11*diag(length(d11))


$$P_2$$


















